apiVersion: v1
kind: Pod
metadata:
  name: azparity-process-health
  labels:
    app: azparity-process-health
spec:
  containers:
  - name: process
    image: gsacavdm/azparity-process:0.0.3
    imagePullPolicy: Always
    env:
    - name: FILE
      value: health.js
    - name: HOSTNAME
      valueFrom:
        secretKeyRef:
          name: mongo
          key: hostname
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mongo
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongo
          key: password

